ALTER TABLE FACT_PC_SALES ADD CONSTRAINT FK_Customer FOREIGN KEY (CustomerID) REFERENCES DIM_CUSTOMER(Customer_ID);
ALTER TABLE FACT_PC_SALES ADD CONSTRAINT FK_Date FOREIGN KEY (Date_Key) REFERENCES DIM_Date(Date_ID);
ALTER TABLE FACT_PC_SALES ADD CONSTRAINT FK_Product FOREIGN KEY (ProductID) REFERENCES DIM_PRODUCT(Product_ID);